### ISSUE TITLE
Finding location of Natural voices

### ISSUE THREAD

**Issue by PaulBlenkhorn** [gexgd0419/NaturalVoiceSAPIAdapter#11]
I want to check if there are any more Natural Voices from Microsoft.  How do we check for more and update your list at:
https://github.com/gexgd0419/NaturalVoiceSAPIAdapter/wiki/Narrator-natural-voice-download-links

**Comment by gexgd0419** [comment]
I just installed every Narrator voice in Settings > Narrator > Add natural voices, and got their Microsoft Store links by copying their links in Microsoft Store.

**Comment by sensoryapphouse** [comment]
Thanks for the quick reply. 
Very interesting. I lived in on a UK windows machine but can only see 3 USA English voices. I also can’t see the links to the Microsoft Store - choosing a voice just downloads it :(

**Comment by sensoryapphouse** [comment]
FYI: the problem was that I was on Windows 11 22h2.  When I change to 23H2 all the voices become available.
