### ISSUE TITLE
<HELP> Microsoft natural voices wont show up in balabolka

### ISSUE THREAD

**Issue by demnuts666** [gexgd0419/NaturalVoiceSAPIAdapter#12]
I have windows 11 and I've downloaded the "NATURALVOICESSAPIADAPTER" too.

I've used the voices back when I had windows 10, with the same software (balabolka, the adapter, natural voices from Microsoft store like Ryan and guy)

But then I reset my pc because of some HDD issues, and the voices disappeared, only the online voices like ryan online show in balabolka. But the natural voices like ryan and guy show in the natural voices narrator in settings.

The voices also show up in the TTSdemo application, they arent just showing up in 

Ive redownloaded balabolka, the sapiadapter, and the voices, no luck

**Comment by gexgd0419** [comment]
A new version [v0.2](https://github.com/gexgd0419/NaturalVoiceSAPIAdapter/releases/tag/v0.2) has been released. You can install both 32-bit and 64-bit, and check if this problem still exists in this version.

**Comment by demnuts666** [comment]
> A new version [v0.2](https://github.com/gexgd0419/NaturalVoiceSAPIAdapter/releases/tag/v0.2) has been released. You can install both 32-bit and 64-bit, and check if this problem still exists in this version.

You cant even imagine how grateful I am right now
Thank You
