### ISSUE TITLE
add profiles

### ISSUE THREAD

**Issue by fireheart2008** [gexgd0419/NaturalVoiceSAPIAdapter#22]
Briliant app!
small changes can improve it
when i open the app everytime it resets the voice and the format. However, I want it to keep my changes so maybe..

1. add the option to save a profile of the favorite voice and format 
2. ability to change default format & voice

**Comment by gexgd0419** [comment]
Do you mean the [TtsApplication](https://github.com/gexgd0419/TTSApplicationSample) included for testing the engine?

It's a (slightly modified) sample project included in the Speech SDK from Microsoft, so it only demonstrates some basic features of the SAPI TTS system, and is included in this program's release package just for convenience.

Its default voice is the system default SAPI TTS voice, and you can change the system default voice in the (old) Control Panel > Speech Recognition > Text to Speech dialog. (Not the one in the new system settings in Windows 10/11, which controls the default OneCore voice, not SAPI voice) And the default format is usually based on the default voice.

If you want a TTS app with more features, you can try [Balabolka](https://www.cross-plus-a.com/balabolka.htm), which can also use the voices from this engine.
