### ISSUE TITLE
Installer error

### ISSUE THREAD

**Issue by hwangsihu** [gexgd0419/NaturalVoiceSAPIAdapter#23]
It installs even though I unchecked Edge Online Voice Checkbox.

**Comment by gexgd0419** [comment]
The Install button installs an "voice enumerator" into the system, which dynamically generates a list of voices, based on the settings stored in the registry. And the installer will only store the changed settings into the registry when the dialog is closed.

If you unchecked the checkbox for Edge voices but they still show up in the list, first make sure the checkbox is unchecked, close the installer dialog, then restart the TTS client application you are using to refresh the voice list.

**Comment by hwangsihu** [comment]
It seems to be resolved, but it would be nice if it applied immediately instead of exiting when the settings are changed.

**Comment by gexgd0419** [comment]
The latest release [v0.2.1](https://github.com/gexgd0419/NaturalVoiceSAPIAdapter/releases/tag/v0.2.1) now saves your changes immediately in the main dialog. Other dialogs still require you to click OK.

**Comment by hwangsihu** [comment]
Thanks
