### ISSUE TITLE
Web Speech API 和balabolka 调用支持

### ISSUE THREAD

**Issue by Pomir** [gexgd0419/NaturalVoiceSAPIAdapter#27]
开发者你好，首先感谢你的辛勤付出，目前已经实现win10 发音人调用离线 Xiaoxiao，但在浏览器读取发音人列表中无 Xiaoxiao，balabolka也无法调用。
请问是否可以提供支持浏览器 Web Speech API 调用离线Xiaoxiao，或者balabolka 调用离线Xiaoxiao

**Comment by gexgd0419** [comment]
Chrome 以及其他 Chromium 浏览器及软件（包括使用 Electron 等制作的软件）只支持 OneCore 语音，不支持 SAPI5 语音。本引擎是 SAPI5 引擎，因此目前无法在这些软件中使用。而微软官方对于如何开发第三方 OneCore 语音没有任何文档说明，还在[文档](https://learn.microsoft.com/en-us/uwp/api/windows.media.speechsynthesis.speechsynthesizer?view=winrt-22621)中表示 OneCore 语音必须经过微软的签名才能使用，所以我暂时没有什么办法。

不过据我所知，Firefox 是支持 SAPI5 语音的，所以在 Firefox 中可以借助 Web Speech API 来调用本引擎的语音。

相关 issue：#4，#5，#24。

另外，Balabolka 是支持本引擎的语音的。Balabolka 应该是 32 位程序，所以需要安装 32 位的版本。安装后就可以在 SAPI5 语音列表里看到了。

注意安装程序的“32位”和“64位”指的是使用语音的程序而不是系统本身，因为32位和64位的程序分别需要32位和64位的组件，所以是可以分别安装的。如果不确定程序是32位还是64位，可以两个都安装。

或许我把两个安装按钮合并，做成一键安装，会更好一些？

**Comment by Pomir** [comment]
谢谢您的耐心解答，我重新安装了32位程序，确实已经支持balabolka，测试firefox也确实支持，感谢
