### ISSUE TITLE
关于晓晓新文件崩溃问题

### ISSUE THREAD

**Issue by godwdss** [gexgd0419/NaturalVoiceSAPIAdapter#35]
0

**Comment by gexgd0419** [comment]
我暂时未能复现崩溃问题。请提供以下信息，以方便复现问题：

- 使用的 NaturalVoiceSAPIAdapter 的版本
- Windows 系统的版本
- 使用的 TTS 客户端软件的名称和版本（最好提供下载方式）
- 语音文件夹在你的系统上存放的完整路径（路径有时也会带来问题，例如英文单引号和非ASCII字符）
- 软件“崩溃”的具体表现，是单纯的无声还是让整个软件退出？
- 相关日志（如果有）

**Comment by godwdss** [comment]
1.每个版本都一样
2.Windows 10 IoT 企业版 LTSC 22H2
3.Balabolka，朗读女，Textaloud情况一样
4.D:\Software\TTS\Microsoft\Win\o\MicrosoftWindows.Voice.zh-CN.Xiaoxiao.1_1.0.9.0_x64__cw5n1h2txyewy
5.会读一个完整的句子后整个朗读程序无响应然后崩溃退出，如果你只用TtsApplication.exe测试，那是没问题，但如果用其他朗读软件，问题都一样。

**Comment by gexgd0419** [comment]
复现了这个问题。使用TtsApplication也能够复现。这个问题神奇的地方在于，32位版本会出问题，但是64位版本则看起来没有问题。

问题体现在，合成语音经常失败（E_FAIL）导致跳过句子，语音的音频有时会出问题，最终会在某个随机的DLL模块中触发Access Violation。

安卓那边没问题，大概是因为安卓那边是64位，但是Windows上的32位程序还有很多，包括Balabolka一类都是32位的。

具体原因需要进一步分析。

另外，这个晓晓的语音数据来自哪里？

**Comment by godwdss** [comment]
BYD车机

**Comment by godwdss** [comment]
我记得不需要64位朗读软件就可以调用64位的语音库的

**Comment by gexgd0419** [comment]
Windows的SAPI5 TTS引擎是进程内COM组件，注入到进程内部的，因此，32位程序只能加载32位版本，64位程序只能加载64位版本。注册表信息也是分开的。

如果要跨架构调用语音库，就必须自行实现跨进程通信。

**Comment by gexgd0419** [comment]
这个问题似乎在Speech SDK的内部，ONNX Runtime会抛出异常，有时还会损坏内存。

Speech SDK不开源，所以我暂时也没有修复方法。

不过还是不太理解，为什么同一个SDK的32/64位版本，会有不同的行为。

另外微软商店的晓晓语音应该还是能用的。

**Comment by godwdss** [comment]
> Windows的SAPI5 TTS引擎是进程内COM组件，注入到进程内部的，因此，32位程序只能加载32位版本，64位程序只能加载64位版本。注册表信息也是分开的。
> 
> 如果要跨架构调用语音库，就必须自行实现跨进程通信。

大佬，我找到了支持64位sapi5软件，格式工厂。不过有一个问题，我之所以用第三方软件就是需要2个功能，批量转换和标点符号停顿设置。由于微软语音在。？！这些句子结束符号不停顿，听起来很难受，大佬能不能在NaturalVoiceSAPIAdapter添加这些标点符号停顿的设置？
