### ISSUE TITLE
请问如何显示在系统的TTS设置中？

### ISSUE THREAD

**Issue by Leroy-X** [gexgd0419/NaturalVoiceSAPIAdapter#5]
![image](https://github.com/gexgd0419/NaturalVoiceSAPIAdapter/assets/13515498/945fbd29-8965-43d4-a46b-c7455c4bf1f2)

已正确安装，可以在Balabolka中选择运行。
请问可以显示在系统设置中吗。一些阅读软件好像是直接调用的系统朗读。只能使用系统所选的默认引擎。

非常感谢如此强大的项目！！！

**Comment by gexgd0419** [comment]
Windows 里包含的语音系统不止一个，SAPI 5 只是其中一个。

打开 控制面板 > 语音 (Windows XP)，或 控制面板 > 语音识别 > 文本到语音转换 (Windows Vista 及以后)，看到的语音才是 SAPI 5 语音。注意不是新的系统设置，而是旧的控制面板。

![语音属性、文本到语音转换页面截图](https://github.com/gexgd0419/NaturalVoiceSAPIAdapter/assets/55008943/b5501077-7538-4251-b45d-c69a2897fa02)

SAPI 5 系统从 Windows XP 时代就开始内置在系统中了，并且它有较好的可扩展性，可以安装第三方制作的语音 TTS 引擎。我的这个程序就是参考微软的 [SAPI 5 开发者文档](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ms717037(v=vs.85)) 制作的。

而新的系统设置里 时间和语言 > 语音 中提供的语音列表，则是来自另一套语音系统，我称之为 OneCore 语音。这个语音系统是 Win 8 开始向移动端应用提供的，后来也出现在了桌面端的 Win 10/11 中，用于向 Metro/UWP 应用提供语音功能。

对于 UWP 应用而言，OneCore 语音基本上就是唯一能用的语音系统，因此 UWP 应用一般不支持 SAPI 5 语音。而非 UWP 应用则可以自行选择支持哪个语音系统，只不过不同的语音系统也要编写不同的代码，所以有些应用可能两个都支持，有些可能只支持其中一个。比如，Chromium 系浏览器就不支持 SAPI 5 语音，包括 Chromium Edge，而 Firefox 就支持。（不过话说 Chromium Edge 的支持也没有必要，毕竟这些语音就是从 Edge 来的……）

最后就是自然语音所使用的又一套语音系统了，实际上就是 Azure Speech SDK。这个程序的作用，就是把 SAPI 5 系统的指令翻译成 Azure Speech SDK 使用的指令，加上提取出的讲述人语音的密钥，实现将讲述人语音提供给所有支持 SAPI 5 的 TTS 程序。

我当初也考虑过对接 OneCore 语音系统。可是微软的[官方文档](https://learn.microsoft.com/en-us/uwp/api/windows.media.speechsynthesis.speechsynthesizer?view=winrt-22621)里是这么说的：

> Only **Microsoft-signed** voices installed on the system can be used to generate speech.

能够正常使用的 OneCore 语音，**必须具有微软的签名！**

就凭这一点，支持 OneCore 怕是不可能了，这个本身就“破解”了微软自然语音的项目是不可能拿到微软官方的认证的……
